/**
 * CRUD Generator for Supabase Edge Functions
 * 
 * Generates complete CRUD Edge Functions with validation, error handling, and middleware
 */

import { stringUtils } from '@brickend/core';
import type {
    Entity,
    Field,
    FieldType
} from '@brickend/core';
import type {
    SupabaseConfig,
    DatabaseSchema,
    EdgeFunctionConfig
} from '../types/index.js';

/**
 * CRUD generation options
 */
interface CRUDGenerationOptions {
    includeAuth?: boolean;
    includeValidation?: boolean;
    includeErrorHandling?: boolean;
    includeCors?: boolean;
    includeLogging?: boolean;
    includePagination?: boolean;
    includeFiltering?: boolean;
    includeSorting?: boolean;
    includeRateLimit?: boolean;
    typescript?: boolean;
}

/**
 * Generated function result
 */
interface GeneratedFunction {
    filename: string;
    content: string;
    method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
    endpoint: string;
    description: string;
}

/**
 * CRUD Generator - Creates complete CRUD Edge Functions
 */
export class CRUDGenerator {
    private readonly config: SupabaseConfig;
    private readonly schema: DatabaseSchema;

    constructor(config: SupabaseConfig, schema: DatabaseSchema) {
        this.config = config;
        this.schema = schema;
    }

    /**
     * Generate complete CRUD function for an entity
     */
    async generateCRUDFunction(
        entity: Entity,
        options: CRUDGenerationOptions = {}
    ): Promise<GeneratedFunction[]> {
        const {
            includeAuth = true,
            includeValidation = true,
            includeErrorHandling = true,
            includeCors = true,
            includeLogging = true,
            includePagination = true,
            includeFiltering = true,
            includeSorting = true,
            includeRateLimit = false,
            typescript = true
        } = options;

        const functions: GeneratedFunction[] = [];
        const tableName = this.getTableName(entity);
        const entityName = stringUtils.camelCase(entity.name);

        // Generate CREATE function
        functions.push(await this.generateCreateFunction(entity, options));

        // Generate READ functions (single + list)
        functions.push(await this.generateReadFunction(entity, options));
        functions.push(await this.generateListFunction(entity, options));

        // Generate UPDATE function
        functions.push(await this.generateUpdateFunction(entity, options));

        // Generate DELETE function
        functions.push(await this.generateDeleteFunction(entity, options));

        // Generate aggregate function (optional)
        if (includeFiltering || includeSorting) {
            functions.push(await this.generateAggregateFunction(entity, options));
        }

        return functions;
    }

    /**
     * Generate validation schemas using Zod
     */
    async generateValidationSchemas(entity: Entity): Promise<string> {
        const code: string[] = [];
        const entityName = stringUtils.pascalCase(entity.name);

        // Add file header
        code.push('/**');
        code.push(` * Validation schemas for ${entity.name}`);
        code.push(' * Generated by Brickend - DO NOT EDIT');
        code.push(' */');
        code.push('');

        // Add imports
        code.push("import { z } from 'zod';");
        code.push('');

        // Generate field schemas
        const fieldSchemas: string[] = [];

        for (const field of entity.fields) {
            const zodSchema = this.generateZodSchema(field);
            fieldSchemas.push(`  ${field.name}: ${zodSchema}`);
        }

        // Create schema
        code.push(`// ${entityName} validation schema`);
        code.push(`export const ${entityName}Schema = z.object({`);
        code.push(fieldSchemas.join(',\n'));
        code.push('});');
        code.push('');

        // Create partial schema for updates
        code.push(`// ${entityName} partial schema for updates`);
        code.push(`export const ${entityName}UpdateSchema = ${entityName}Schema.partial();`);
        code.push('');

        // Create query schema for list operations
        code.push(`// ${entityName} query schema for filtering`);
        code.push(`export const ${entityName}QuerySchema = z.object({`);
        code.push('  page: z.coerce.number().min(1).default(1),');
        code.push('  limit: z.coerce.number().min(1).max(100).default(10),');
        code.push('  sort: z.string().optional(),');
        code.push('  order: z.enum(["asc", "desc"]).default("asc"),');

        // Add filterable fields
        for (const field of entity.fields) {
            if (this.isFilterableField(field)) {
                code.push(`  ${field.name}: z.string().optional(),`);
            }
        }

        code.push('});');
        code.push('');

        // Export types
        code.push(`// TypeScript types`);
        code.push(`export type ${entityName} = z.infer<typeof ${entityName}Schema>;`);
        code.push(`export type ${entityName}Update = z.infer<typeof ${entityName}UpdateSchema>;`);
        code.push(`export type ${entityName}Query = z.infer<typeof ${entityName}QuerySchema>;`);

        return code.join('\n');
    }

    /**
     * Generate error handlers
     */
    async generateErrorHandlers(): Promise<string> {
        const code: string[] = [];

        // Add file header
        code.push('/**');
        code.push(' * Error handlers for Edge Functions');
        code.push(' * Generated by Brickend - DO NOT EDIT');
        code.push(' */');
        code.push('');

        // Error types
        code.push('export enum ErrorCode {');
        code.push('  VALIDATION_ERROR = "VALIDATION_ERROR",');
        code.push('  NOT_FOUND = "NOT_FOUND",');
        code.push('  UNAUTHORIZED = "UNAUTHORIZED",');
        code.push('  FORBIDDEN = "FORBIDDEN",');
        code.push('  CONFLICT = "CONFLICT",');
        code.push('  RATE_LIMITED = "RATE_LIMITED",');
        code.push('  INTERNAL_ERROR = "INTERNAL_ERROR"');
        code.push('}');
        code.push('');

        // Error response interface
        code.push('export interface ErrorResponse {');
        code.push('  error: {');
        code.push('    code: ErrorCode;');
        code.push('    message: string;');
        code.push('    details?: any;');
        code.push('    timestamp: string;');
        code.push('  };');
        code.push('}');
        code.push('');

        // Error handler function
        code.push('/**');
        code.push(' * Handle and format errors consistently');
        code.push(' */');
        code.push('export function handleError(error: any): Response {');
        code.push('  console.error("Edge Function Error:", error);');
        code.push('');
        code.push('  let statusCode = 500;');
        code.push('  let errorCode = ErrorCode.INTERNAL_ERROR;');
        code.push('  let message = "Internal server error";');
        code.push('  let details = undefined;');
        code.push('');
        code.push('  // Handle Zod validation errors');
        code.push('  if (error.name === "ZodError") {');
        code.push('    statusCode = 400;');
        code.push('    errorCode = ErrorCode.VALIDATION_ERROR;');
        code.push('    message = "Validation failed";');
        code.push('    details = error.errors;');
        code.push('  }');
        code.push('');
        code.push('  // Handle Supabase errors');
        code.push('  else if (error.code) {');
        code.push('    switch (error.code) {');
        code.push('      case "23505": // Unique violation');
        code.push('        statusCode = 409;');
        code.push('        errorCode = ErrorCode.CONFLICT;');
        code.push('        message = "Resource already exists";');
        code.push('        break;');
        code.push('      case "23503": // Foreign key violation');
        code.push('        statusCode = 400;');
        code.push('        errorCode = ErrorCode.VALIDATION_ERROR;');
        code.push('        message = "Invalid reference";');
        code.push('        break;');
        code.push('      case "42501": // Insufficient privilege');
        code.push('        statusCode = 403;');
        code.push('        errorCode = ErrorCode.FORBIDDEN;');
        code.push('        message = "Insufficient permissions";');
        code.push('        break;');
        code.push('      default:');
        code.push('        message = error.message || "Database error";');
        code.push('    }');
        code.push('  }');
        code.push('');
        code.push('  // Handle custom application errors');
        code.push('  else if (error.statusCode) {');
        code.push('    statusCode = error.statusCode;');
        code.push('    errorCode = error.code || ErrorCode.INTERNAL_ERROR;');
        code.push('    message = error.message;');
        code.push('    details = error.details;');
        code.push('  }');
        code.push('');
        code.push('  const errorResponse: ErrorResponse = {');
        code.push('    error: {');
        code.push('      code: errorCode,');
        code.push('      message,');
        code.push('      details,');
        code.push('      timestamp: new Date().toISOString()');
        code.push('    }');
        code.push('  };');
        code.push('');
        code.push('  return new Response(JSON.stringify(errorResponse), {');
        code.push('    status: statusCode,');
        code.push('    headers: { "Content-Type": "application/json" }');
        code.push('  });');
        code.push('}');
        code.push('');

        // Success response helper
        code.push('/**');
        code.push(' * Create success response');
        code.push(' */');
        code.push('export function successResponse(data: any, status: number = 200): Response {');
        code.push('  return new Response(JSON.stringify(data), {');
        code.push('    status,');
        code.push('    headers: { "Content-Type": "application/json" }');
        code.push('  });');
        code.push('}');
        code.push('');

        // Not found helper
        code.push('/**');
        code.push(' * Create not found response');
        code.push(' */');
        code.push('export function notFoundResponse(resource: string = "Resource"): Response {');
        code.push('  const errorResponse: ErrorResponse = {');
        code.push('    error: {');
        code.push('      code: ErrorCode.NOT_FOUND,');
        code.push('      message: `${resource} not found`,');
        code.push('      timestamp: new Date().toISOString()');
        code.push('    }');
        code.push('  };');
        code.push('');
        code.push('  return new Response(JSON.stringify(errorResponse), {');
        code.push('    status: 404,');
        code.push('    headers: { "Content-Type": "application/json" }');
        code.push('  });');
        code.push('}');

        return code.join('\n');
    }

    /**
     * Generate common middleware
     */
    async generateMiddleware(): Promise<string> {
        const code: string[] = [];

        // Add file header
        code.push('/**');
        code.push(' * Common middleware for Edge Functions');
        code.push(' * Generated by Brickend - DO NOT EDIT');
        code.push(' */');
        code.push('');

        // Add imports
        code.push("import { createClient } from '@supabase/supabase-js';");
        code.push("import { handleError } from './error-handlers.js';");
        code.push('');

        // CORS middleware
        code.push('/**');
        code.push(' * CORS middleware');
        code.push(' */');
        code.push('export function corsHeaders(origin?: string) {');
        code.push('  return {');
        code.push('    "Access-Control-Allow-Origin": origin || "*",');
        code.push('    "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",');
        code.push('    "Access-Control-Allow-Methods": "GET, POST, PUT, PATCH, DELETE, OPTIONS"');
        code.push('  };');
        code.push('}');
        code.push('');

        code.push('/**');
        code.push(' * Handle CORS preflight requests');
        code.push(' */');
        code.push('export function handleCors(request: Request): Response | null {');
        code.push('  if (request.method === "OPTIONS") {');
        code.push('    return new Response(null, {');
        code.push('      status: 200,');
        code.push('      headers: corsHeaders()');
        code.push('    });');
        code.push('  }');
        code.push('  return null;');
        code.push('}');
        code.push('');

        // Auth middleware
        code.push('/**');
        code.push(' * Authentication middleware');
        code.push(' */');
        code.push('export async function requireAuth(request: Request) {');
        code.push('  const authHeader = request.headers.get("Authorization");');
        code.push('  if (!authHeader) {');
        code.push('    throw { statusCode: 401, message: "Authorization header required" };');
        code.push('  }');
        code.push('');
        code.push('  const token = authHeader.replace("Bearer ", "");');
        code.push('  const supabase = createClient(');
        code.push(`    Deno.env.get("SUPABASE_URL")!,`);
        code.push(`    Deno.env.get("SUPABASE_ANON_KEY")!`);
        code.push('  );');
        code.push('');
        code.push('  const { data: { user }, error } = await supabase.auth.getUser(token);');
        code.push('  if (error || !user) {');
        code.push('    throw { statusCode: 401, message: "Invalid token" };');
        code.push('  }');
        code.push('');
        code.push('  return user;');
        code.push('}');
        code.push('');

        // Database client
        code.push('/**');
        code.push(' * Get authenticated Supabase client');
        code.push(' */');
        code.push('export function getSupabaseClient(authToken?: string) {');
        code.push('  const client = createClient(');
        code.push(`    Deno.env.get("SUPABASE_URL")!,`);
        code.push(`    Deno.env.get("SUPABASE_ANON_KEY")!,`);
        code.push('    authToken ? {');
        code.push('      global: {');
        code.push('        headers: { Authorization: `Bearer ${authToken}` }');
        code.push('      }');
        code.push('    } : {}');
        code.push('  );');
        code.push('');
        code.push('  return client;');
        code.push('}');
        code.push('');

        // Logging middleware
        code.push('/**');
        code.push(' * Request logging middleware');
        code.push(' */');
        code.push('export function logRequest(request: Request, startTime: number) {');
        code.push('  const duration = Date.now() - startTime;');
        code.push('  console.log(`${request.method} ${request.url} - ${duration}ms`);');
        code.push('}');
        code.push('');

        // Rate limiting
        code.push('/**');
        code.push(' * Simple rate limiting (in-memory)');
        code.push(' */');
        code.push('const rateLimitMap = new Map<string, number[]>();');
        code.push('');
        code.push('export function checkRateLimit(');
        code.push('  identifier: string,');
        code.push('  maxRequests: number = 100,');
        code.push('  windowMs: number = 60000');
        code.push('): boolean {');
        code.push('  const now = Date.now();');
        code.push('  const windowStart = now - windowMs;');
        code.push('');
        code.push('  if (!rateLimitMap.has(identifier)) {');
        code.push('    rateLimitMap.set(identifier, []);');
        code.push('  }');
        code.push('');
        code.push('  const requests = rateLimitMap.get(identifier)!;');
        code.push('  const recentRequests = requests.filter(time => time > windowStart);');
        code.push('');
        code.push('  if (recentRequests.length >= maxRequests) {');
        code.push('    return false;');
        code.push('  }');
        code.push('');
        code.push('  recentRequests.push(now);');
        code.push('  rateLimitMap.set(identifier, recentRequests);');
        code.push('  return true;');
        code.push('}');
        code.push('');

        // Pagination helper
        code.push('/**');
        code.push(' * Pagination helper');
        code.push(' */');
        code.push('export function getPaginationParams(url: URL) {');
        code.push('  const page = Math.max(1, parseInt(url.searchParams.get("page") || "1"));');
        code.push('  const limit = Math.min(100, Math.max(1, parseInt(url.searchParams.get("limit") || "10")));');
        code.push('  const offset = (page - 1) * limit;');
        code.push('');
        code.push('  return { page, limit, offset };');
        code.push('}');

        return code.join('\n');
    }

    /**
     * Generate CREATE function
     */
    private async generateCreateFunction(entity: Entity, options: CRUDGenerationOptions): Promise<GeneratedFunction> {
        const entityName = stringUtils.pascalCase(entity.name);
        const tableName = this.getTableName(entity);
        const code: string[] = [];

        // Function header
        code.push(this.generateFunctionHeader(`Create ${entity.name}`, 'POST', `/${stringUtils.kebabCase(entity.name)}`));

        // Imports
        code.push("import { createClient } from '@supabase/supabase-js';");
        if (options.includeValidation) {
            code.push(`import { ${entityName}Schema } from '../shared/validation.ts';`);
        }
        if (options.includeErrorHandling) {
            code.push("import { handleError, successResponse } from '../shared/error-handlers.ts';");
        }
        if (options.includeCors || options.includeAuth) {
            code.push("import { handleCors, requireAuth, getSupabaseClient, corsHeaders } from '../shared/middleware.ts';");
        }
        code.push('');

        // Main function
        code.push(`Deno.serve(async (req: Request) => {`);
        code.push('  try {');

        // CORS handling
        if (options.includeCors) {
            code.push('    const corsResponse = handleCors(req);');
            code.push('    if (corsResponse) return corsResponse;');
            code.push('');
        }

        // Method validation
        code.push('    if (req.method !== "POST") {');
        code.push('      return new Response("Method not allowed", { status: 405 });');
        code.push('    }');
        code.push('');

        // Authentication
        if (options.includeAuth) {
            code.push('    const user = await requireAuth(req);');
            code.push('    const authToken = req.headers.get("Authorization")?.replace("Bearer ", "");');
            code.push('');
        }

        // Parse request body
        code.push('    const body = await req.json();');
        code.push('');

        // Validation
        if (options.includeValidation) {
            code.push(`    const validatedData = ${entityName}Schema.parse(body);`);
        } else {
            code.push('    const validatedData = body;');
        }
        code.push('');

        // Add user ID if authenticated
        if (options.includeAuth) {
            code.push('    // Add user context');
            code.push('    const dataWithUser = { ...validatedData, user_id: user.id };');
            code.push('');
        }

        // Database operation
        code.push('    const supabase = getSupabaseClient(authToken);');
        code.push(`    const { data, error } = await supabase`);
        code.push(`      .from('${tableName}')`);
        code.push(`      .insert(${options.includeAuth ? 'dataWithUser' : 'validatedData'})`);
        code.push('      .select()');
        code.push('      .single();');
        code.push('');

        code.push('    if (error) throw error;');
        code.push('');

        // Return response
        if (options.includeErrorHandling) {
            code.push('    return successResponse(data, 201);');
        } else {
            code.push('    return new Response(JSON.stringify(data), {');
            code.push('      status: 201,');
            code.push('      headers: { "Content-Type": "application/json", ...corsHeaders() }');
            code.push('    });');
        }

        // Error handling
        code.push('  } catch (error) {');
        if (options.includeErrorHandling) {
            code.push('    return handleError(error);');
        } else {
            code.push('    return new Response(JSON.stringify({ error: error.message }), {');
            code.push('      status: 500,');
            code.push('      headers: { "Content-Type": "application/json" }');
            code.push('    });');
        }
        code.push('  }');
        code.push('});');

        return {
            filename: `create-${stringUtils.kebabCase(entity.name)}.ts`,
            content: code.join('\n'),
            method: 'POST',
            endpoint: `/${stringUtils.kebabCase(entity.name)}`,
            description: `Create a new ${entity.name}`
        };
    }

    /**
     * Generate READ function (single item)
     */
    private async generateReadFunction(entity: Entity, options: CRUDGenerationOptions): Promise<GeneratedFunction> {
        const entityName = stringUtils.pascalCase(entity.name);
        const tableName = this.getTableName(entity);
        const code: string[] = [];

        // Function header
        code.push(this.generateFunctionHeader(`Get ${entity.name}`, 'GET', `/${stringUtils.kebabCase(entity.name)}/[id]`));

        // Imports
        code.push("import { createClient } from '@supabase/supabase-js';");
        if (options.includeErrorHandling) {
            code.push("import { handleError, successResponse, notFoundResponse } from '../shared/error-handlers.ts';");
        }
        if (options.includeCors || options.includeAuth) {
            code.push("import { handleCors, requireAuth, getSupabaseClient, corsHeaders } from '../shared/middleware.ts';");
        }
        code.push('');

        // Main function
        code.push(`Deno.serve(async (req: Request) => {`);
        code.push('  try {');

        // CORS handling
        if (options.includeCors) {
            code.push('    const corsResponse = handleCors(req);');
            code.push('    if (corsResponse) return corsResponse;');
            code.push('');
        }

        // Method validation
        code.push('    if (req.method !== "GET") {');
        code.push('      return new Response("Method not allowed", { status: 405 });');
        code.push('    }');
        code.push('');

        // Extract ID from URL
        code.push('    const url = new URL(req.url);');
        code.push('    const id = url.pathname.split("/").pop();');
        code.push('    if (!id) {');
        code.push('      throw { statusCode: 400, message: "ID parameter required" };');
        code.push('    }');
        code.push('');

        // Authentication (optional for reads)
        if (options.includeAuth) {
            code.push('    const user = await requireAuth(req);');
            code.push('    const authToken = req.headers.get("Authorization")?.replace("Bearer ", "");');
            code.push('');
        }

        // Database operation
        code.push('    const supabase = getSupabaseClient(authToken);');
        code.push(`    let query = supabase.from('${tableName}').select().eq('id', id);`);

        // Add user filter if authenticated
        if (options.includeAuth) {
            code.push('    query = query.eq("user_id", user.id);');
        }

        code.push('    const { data, error } = await query.single();');
        code.push('');

        code.push('    if (error) {');
        code.push('      if (error.code === "PGRST116") {');
        if (options.includeErrorHandling) {
            code.push(`        return notFoundResponse("${entity.name}");`);
        } else {
            code.push('        return new Response("Not found", { status: 404 });');
        }
        code.push('      }');
        code.push('      throw error;');
        code.push('    }');
        code.push('');

        // Return response
        if (options.includeErrorHandling) {
            code.push('    return successResponse(data);');
        } else {
            code.push('    return new Response(JSON.stringify(data), {');
            code.push('      headers: { "Content-Type": "application/json", ...corsHeaders() }');
            code.push('    });');
        }

        // Error handling
        code.push('  } catch (error) {');
        if (options.includeErrorHandling) {
            code.push('    return handleError(error);');
        } else {
            code.push('    return new Response(JSON.stringify({ error: error.message }), {');
            code.push('      status: 500,');
            code.push('      headers: { "Content-Type": "application/json" }');
            code.push('    });');
        }
        code.push('  }');
        code.push('});');

        return {
            filename: `get-${stringUtils.kebabCase(entity.name)}.ts`,
            content: code.join('\n'),
            method: 'GET',
            endpoint: `/${stringUtils.kebabCase(entity.name)}/[id]`,
            description: `Get a single ${entity.name} by ID`
        };
    }

    /**
     * Generate LIST function (multiple items with pagination)
     */
    private async generateListFunction(entity: Entity, options: CRUDGenerationOptions): Promise<GeneratedFunction> {
        const entityName = stringUtils.pascalCase(entity.name);
        const tableName = this.getTableName(entity);
        const code: string[] = [];

        // Function header
        code.push(this.generateFunctionHeader(`List ${entity.name}s`, 'GET', `/${stringUtils.kebabCase(entity.name)}`));

        // Imports
        code.push("import { createClient } from '@supabase/supabase-js';");
        if (options.includeValidation) {
            code.push(`import { ${entityName}QuerySchema } from '../shared/validation.ts';`);
        }
        if (options.includeErrorHandling) {
            code.push("import { handleError, successResponse } from '../shared/error-handlers.ts';");
        }
        if (options.includeCors || options.includeAuth || options.includePagination) {
            code.push("import { handleCors, requireAuth, getSupabaseClient, corsHeaders, getPaginationParams } from '../shared/middleware.ts';");
        }
        code.push('');

        // Main function
        code.push(`Deno.serve(async (req: Request) => {`);
        code.push('  try {');

        // CORS handling
        if (options.includeCors) {
            code.push('    const corsResponse = handleCors(req);');
            code.push('    if (corsResponse) return corsResponse;');
            code.push('');
        }

        // Method validation
        code.push('    if (req.method !== "GET") {');
        code.push('      return new Response("Method not allowed", { status: 405 });');
        code.push('    }');
        code.push('');

        // Parse query parameters
        code.push('    const url = new URL(req.url);');
        if (options.includePagination) {
            code.push('    const { page, limit, offset } = getPaginationParams(url);');
        }
        code.push('');

        // Validation of query params
        if (options.includeValidation) {
            code.push('    const queryParams = Object.fromEntries(url.searchParams);');
            code.push(`    const validatedQuery = ${entityName}QuerySchema.parse(queryParams);`);
        }
        code.push('');

        // Authentication (optional for reads)
        if (options.includeAuth) {
            code.push('    const user = await requireAuth(req);');
            code.push('    const authToken = req.headers.get("Authorization")?.replace("Bearer ", "");');
            code.push('');
        }

        // Database operation
        code.push('    const supabase = getSupabaseClient(authToken);');
        code.push(`    let query = supabase.from('${tableName}').select('*', { count: 'exact' });`);

        // Add user filter if authenticated
        if (options.includeAuth) {
            code.push('    query = query.eq("user_id", user.id);');
        }

        // Add filtering
        if (options.includeFiltering) {
            for (const field of entity.fields) {
                if (this.isFilterableField(field)) {
                    code.push(`    if (url.searchParams.get('${field.name}')) {`);
                    code.push(`      query = query.eq('${field.name}', url.searchParams.get('${field.name}'));`);
                    code.push('    }');
                }
            }
        }
        code.push('');

        // Add sorting
        if (options.includeSorting) {
            code.push('    const sortField = url.searchParams.get("sort");');
            code.push('    const sortOrder = url.searchParams.get("order") === "desc" ? false : true;');
            code.push('    if (sortField) {');
            code.push('      query = query.order(sortField, { ascending: sortOrder });');
            code.push('    } else {');
            code.push('      query = query.order("created_at", { ascending: false });');
            code.push('    }');
        }
        code.push('');

        // Add pagination
        if (options.includePagination) {
            code.push('    query = query.range(offset, offset + limit - 1);');
        }
        code.push('');

        code.push('    const { data, error, count } = await query;');
        code.push('');

        code.push('    if (error) throw error;');
        code.push('');

        // Build response with pagination metadata
        if (options.includePagination) {
            code.push('    const response = {');
            code.push('      data,');
            code.push('      pagination: {');
            code.push('        page,');
            code.push('        limit,');
            code.push('        total: count || 0,');
            code.push('        totalPages: Math.ceil((count || 0) / limit)');
            code.push('      }');
            code.push('    };');
            code.push('');
            if (options.includeErrorHandling) {
                code.push('    return successResponse(response);');
            } else {
                code.push('    return new Response(JSON.stringify(response), {');
                code.push('      headers: { "Content-Type": "application/json", ...corsHeaders() }');
                code.push('    });');
            }
        } else {
            if (options.includeErrorHandling) {
                code.push('    return successResponse(data);');
            } else {
                code.push('    return new Response(JSON.stringify(data), {');
                code.push('      headers: { "Content-Type": "application/json", ...corsHeaders() }');
                code.push('    });');
            }
        }

        // Error handling
        code.push('  } catch (error) {');
        if (options.includeErrorHandling) {
            code.push('    return handleError(error);');
        } else {
            code.push('    return new Response(JSON.stringify({ error: error.message }), {');
            code.push('      status: 500,');
            code.push('      headers: { "Content-Type": "application/json" }');
            code.push('    });');
        }
        code.push('  }');
        code.push('});');

        return {
            filename: `list-${stringUtils.kebabCase(entity.name)}s.ts`,
            content: code.join('\n'),
            method: 'GET',
            endpoint: `/${stringUtils.kebabCase(entity.name)}`,
            description: `List ${entity.name}s with pagination and filtering`
        };
    }

    /**
     * Generate UPDATE function
     */
    private async generateUpdateFunction(entity: Entity, options: CRUDGenerationOptions): Promise<GeneratedFunction> {
        const entityName = stringUtils.pascalCase(entity.name);
        const tableName = this.getTableName(entity);
        const code: string[] = [];

        // Function header
        code.push(this.generateFunctionHeader(`Update ${entity.name}`, 'PUT', `/${stringUtils.kebabCase(entity.name)}/[id]`));

        // Imports
        code.push("import { createClient } from '@supabase/supabase-js';");
        if (options.includeValidation) {
            code.push(`import { ${entityName}UpdateSchema } from '../shared/validation.ts';`);
        }
        if (options.includeErrorHandling) {
            code.push("import { handleError, successResponse, notFoundResponse } from '../shared/error-handlers.ts';");
        }
        if (options.includeCors || options.includeAuth) {
            code.push("import { handleCors, requireAuth, getSupabaseClient, corsHeaders } from '../shared/middleware.ts';");
        }
        code.push('');

        // Main function
        code.push(`Deno.serve(async (req: Request) => {`);
        code.push('  try {');

        // CORS handling
        if (options.includeCors) {
            code.push('    const corsResponse = handleCors(req);');
            code.push('    if (corsResponse) return corsResponse;');
            code.push('');
        }

        // Method validation
        code.push('    if (req.method !== "PUT" && req.method !== "PATCH") {');
        code.push('      return new Response("Method not allowed", { status: 405 });');
        code.push('    }');
        code.push('');

        // Extract ID from URL
        code.push('    const url = new URL(req.url);');
        code.push('    const id = url.pathname.split("/").pop();');
        code.push('    if (!id) {');
        code.push('      throw { statusCode: 400, message: "ID parameter required" };');
        code.push('    }');
        code.push('');

        // Authentication
        if (options.includeAuth) {
            code.push('    const user = await requireAuth(req);');
            code.push('    const authToken = req.headers.get("Authorization")?.replace("Bearer ", "");');
            code.push('');
        }

        // Parse request body
        code.push('    const body = await req.json();');
        code.push('');

        // Validation
        if (options.includeValidation) {
            code.push(`    const validatedData = ${entityName}UpdateSchema.parse(body);`);
        } else {
            code.push('    const validatedData = body;');
        }
        code.push('');

        // Add updated_at timestamp
        code.push('    const dataWithTimestamp = {');
        code.push('      ...validatedData,');
        code.push('      updated_at: new Date().toISOString()');
        code.push('    };');
        code.push('');

        // Database operation
        code.push('    const supabase = getSupabaseClient(authToken);');
        code.push(`    let query = supabase.from('${tableName}')`);
        code.push('      .update(dataWithTimestamp)');
        code.push('      .eq("id", id)');

        // Add user filter if authenticated
        if (options.includeAuth) {
            code.push('      .eq("user_id", user.id)');
        }

        code.push('      .select()');
        code.push('      .single();');
        code.push('');

        code.push('    const { data, error } = await query;');
        code.push('');

        code.push('    if (error) {');
        code.push('      if (error.code === "PGRST116") {');
        if (options.includeErrorHandling) {
            code.push(`        return notFoundResponse("${entity.name}");`);
        } else {
            code.push('        return new Response("Not found", { status: 404 });');
        }
        code.push('      }');
        code.push('      throw error;');
        code.push('    }');
        code.push('');

        // Return response
        if (options.includeErrorHandling) {
            code.push('    return successResponse(data);');
        } else {
            code.push('    return new Response(JSON.stringify(data), {');
            code.push('      headers: { "Content-Type": "application/json", ...corsHeaders() }');
            code.push('    });');
        }

        // Error handling
        code.push('  } catch (error) {');
        if (options.includeErrorHandling) {
            code.push('    return handleError(error);');
        } else {
            code.push('    return new Response(JSON.stringify({ error: error.message }), {');
            code.push('      status: 500,');
            code.push('      headers: { "Content-Type": "application/json" }');
            code.push('    });');
        }
        code.push('  }');
        code.push('});');

        return {
            filename: `update-${stringUtils.kebabCase(entity.name)}.ts`,
            content: code.join('\n'),
            method: 'PUT',
            endpoint: `/${stringUtils.kebabCase(entity.name)}/[id]`,
            description: `Update a ${entity.name} by ID`
        };
    }

    /**
     * Generate DELETE function
     */
    private async generateDeleteFunction(entity: Entity, options: CRUDGenerationOptions): Promise<GeneratedFunction> {
        const tableName = this.getTableName(entity);
        const code: string[] = [];

        // Function header
        code.push(this.generateFunctionHeader(`Delete ${entity.name}`, 'DELETE', `/${stringUtils.kebabCase(entity.name)}/[id]`));

        // Imports
        code.push("import { createClient } from '@supabase/supabase-js';");
        if (options.includeErrorHandling) {
            code.push("import { handleError, successResponse, notFoundResponse } from '../shared/error-handlers.ts';");
        }
        if (options.includeCors || options.includeAuth) {
            code.push("import { handleCors, requireAuth, getSupabaseClient, corsHeaders } from '../shared/middleware.ts';");
        }
        code.push('');

        // Main function
        code.push(`Deno.serve(async (req: Request) => {`);
        code.push('  try {');

        // CORS handling
        if (options.includeCors) {
            code.push('    const corsResponse = handleCors(req);');
            code.push('    if (corsResponse) return corsResponse;');
            code.push('');
        }

        // Method validation
        code.push('    if (req.method !== "DELETE") {');
        code.push('      return new Response("Method not allowed", { status: 405 });');
        code.push('    }');
        code.push('');

        // Extract ID from URL
        code.push('    const url = new URL(req.url);');
        code.push('    const id = url.pathname.split("/").pop();');
        code.push('    if (!id) {');
        code.push('      throw { statusCode: 400, message: "ID parameter required" };');
        code.push('    }');
        code.push('');

        // Authentication
        if (options.includeAuth) {
            code.push('    const user = await requireAuth(req);');
            code.push('    const authToken = req.headers.get("Authorization")?.replace("Bearer ", "");');
            code.push('');
        }

        // Database operation (soft delete if enabled, hard delete otherwise)
        code.push('    const supabase = getSupabaseClient(authToken);');

        if (entity.options?.softDelete) {
            code.push('    // Soft delete');
            code.push(`    let query = supabase.from('${tableName}')`);
            code.push('      .update({ deleted_at: new Date().toISOString() })');
            code.push('      .eq("id", id)');

            if (options.includeAuth) {
                code.push('      .eq("user_id", user.id)');
            }

            code.push('      .select()');
            code.push('      .single();');
        } else {
            code.push('    // Hard delete');
            code.push(`    let query = supabase.from('${tableName}')`);
            code.push('      .delete()');
            code.push('      .eq("id", id)');

            if (options.includeAuth) {
                code.push('      .eq("user_id", user.id)');
            }
        }

        code.push('');
        code.push('    const { data, error } = await query;');
        code.push('');

        code.push('    if (error) {');
        code.push('      if (error.code === "PGRST116") {');
        if (options.includeErrorHandling) {
            code.push(`        return notFoundResponse("${entity.name}");`);
        } else {
            code.push('        return new Response("Not found", { status: 404 });');
        }
        code.push('      }');
        code.push('      throw error;');
        code.push('    }');
        code.push('');

        // Return response
        if (options.includeErrorHandling) {
            code.push('    return successResponse({ message: "Deleted successfully" }, 204);');
        } else {
            code.push('    return new Response(null, {');
            code.push('      status: 204,');
            code.push('      headers: corsHeaders()');
            code.push('    });');
        }

        // Error handling
        code.push('  } catch (error) {');
        if (options.includeErrorHandling) {
            code.push('    return handleError(error);');
        } else {
            code.push('    return new Response(JSON.stringify({ error: error.message }), {');
            code.push('      status: 500,');
            code.push('      headers: { "Content-Type": "application/json" }');
            code.push('    });');
        }
        code.push('  }');
        code.push('});');

        return {
            filename: `delete-${stringUtils.kebabCase(entity.name)}.ts`,
            content: code.join('\n'),
            method: 'DELETE',
            endpoint: `/${stringUtils.kebabCase(entity.name)}/[id]`,
            description: `Delete a ${entity.name} by ID`
        };
    }

    /**
     * Generate aggregate function (count, stats, etc.)
     */
    private async generateAggregateFunction(entity: Entity, options: CRUDGenerationOptions): Promise<GeneratedFunction> {
        const tableName = this.getTableName(entity);
        const code: string[] = [];

        // Function header
        code.push(this.generateFunctionHeader(`${entity.name} Statistics`, 'GET', `/${stringUtils.kebabCase(entity.name)}/stats`));

        // Imports
        code.push("import { createClient } from '@supabase/supabase-js';");
        if (options.includeErrorHandling) {
            code.push("import { handleError, successResponse } from '../shared/error-handlers.ts';");
        }
        if (options.includeCors || options.includeAuth) {
            code.push("import { handleCors, requireAuth, getSupabaseClient, corsHeaders } from '../shared/middleware.ts';");
        }
        code.push('');

        // Main function
        code.push(`Deno.serve(async (req: Request) => {`);
        code.push('  try {');

        // CORS handling
        if (options.includeCors) {
            code.push('    const corsResponse = handleCors(req);');
            code.push('    if (corsResponse) return corsResponse;');
            code.push('');
        }

        // Method validation
        code.push('    if (req.method !== "GET") {');
        code.push('      return new Response("Method not allowed", { status: 405 });');
        code.push('    }');
        code.push('');

        // Authentication (optional for stats)
        if (options.includeAuth) {
            code.push('    const user = await requireAuth(req);');
            code.push('    const authToken = req.headers.get("Authorization")?.replace("Bearer ", "");');
            code.push('');
        }

        // Database operations
        code.push('    const supabase = getSupabaseClient(authToken);');
        code.push('');

        // Total count
        code.push('    // Get total count');
        code.push(`    let countQuery = supabase.from('${tableName}').select('*', { count: 'exact', head: true });`);
        if (options.includeAuth) {
            code.push('    countQuery = countQuery.eq("user_id", user.id);');
        }
        code.push('    const { count: totalCount, error: countError } = await countQuery;');
        code.push('    if (countError) throw countError;');
        code.push('');

        // Recent count (last 7 days)
        code.push('    // Get recent count (last 7 days)');
        code.push('    const weekAgo = new Date();');
        code.push('    weekAgo.setDate(weekAgo.getDate() - 7);');
        code.push('');
        code.push(`    let recentQuery = supabase.from('${tableName}').select('*', { count: 'exact', head: true })`);
        code.push('      .gte("created_at", weekAgo.toISOString());');
        if (options.includeAuth) {
            code.push('    recentQuery = recentQuery.eq("user_id", user.id);');
        }
        code.push('    const { count: recentCount, error: recentError } = await recentQuery;');
        code.push('    if (recentError) throw recentError;');
        code.push('');

        // Build stats response
        code.push('    const stats = {');
        code.push('      total: totalCount || 0,');
        code.push('      recent: recentCount || 0,');
        code.push('      generatedAt: new Date().toISOString()');
        code.push('    };');
        code.push('');

        // Return response
        if (options.includeErrorHandling) {
            code.push('    return successResponse(stats);');
        } else {
            code.push('    return new Response(JSON.stringify(stats), {');
            code.push('      headers: { "Content-Type": "application/json", ...corsHeaders() }');
            code.push('    });');
        }

        // Error handling
        code.push('  } catch (error) {');
        if (options.includeErrorHandling) {
            code.push('    return handleError(error);');
        } else {
            code.push('    return new Response(JSON.stringify({ error: error.message }), {');
            code.push('      status: 500,');
            code.push('      headers: { "Content-Type": "application/json" }');
            code.push('    });');
        }
        code.push('  }');
        code.push('});');

        return {
            filename: `stats-${stringUtils.kebabCase(entity.name)}.ts`,
            content: code.join('\n'),
            method: 'GET',
            endpoint: `/${stringUtils.kebabCase(entity.name)}/stats`,
            description: `Get ${entity.name} statistics and aggregates`
        };
    }

    /**
     * Generate function header comment
     */
    private generateFunctionHeader(title: string, method: string, endpoint: string): string {
        return `/**
 * ${title}
 * Method: ${method}
 * Endpoint: ${endpoint}
 * Generated by Brickend - DO NOT EDIT
 */
`;
    }

    /**
     * Generate Zod schema for a field
     */
    private generateZodSchema(field: Field): string {
        let schema = '';

        // Base type
        switch (field.type) {
            case 'string':
            case 'text':
            case 'email':
            case 'url':
            case 'uuid':
                schema = 'z.string()';
                break;
            case 'number':
            case 'integer':
            case 'float':
            case 'decimal':
                schema = 'z.number()';
                break;
            case 'boolean':
                schema = 'z.boolean()';
                break;
            case 'date':
            case 'datetime':
                schema = 'z.string().datetime()';
                break;
            case 'json':
                schema = 'z.any()';
                break;
            default:
                schema = 'z.string()';
        }

        // Add validation rules
        if (field.validation) {
            if (field.type === 'email') {
                schema += '.email()';
            }
            if (field.type === 'url') {
                schema += '.url()';
            }
            if (field.validation.minLength) {
                schema += `.min(${field.validation.minLength})`;
            }
            if (field.validation.maxLength) {
                schema += `.max(${field.validation.maxLength})`;
            }
            if (field.validation.min) {
                schema += `.min(${field.validation.min})`;
            }
            if (field.validation.max) {
                schema += `.max(${field.validation.max})`;
            }
            if (field.validation.pattern) {
                schema += `.regex(/${field.validation.pattern}/)`;
            }
            if (field.validation.enum) {
                schema += `.enum([${field.validation.enum.map(v => `"${v}"`).join(', ')}])`;
            }
        }

        // Make optional if not required
        if (!field.validation?.required || field.options?.nullable) {
            schema += '.optional()';
        }

        return schema;
    }

    /**
     * Check if field is filterable
     */
    private isFilterableField(field: Field): boolean {
        // Allow filtering on most field types except large text and json
        return !['text', 'json'].includes(field.type);
    }

    /**
     * Get table name for entity
     */
    private getTableName(entity: Entity): string {
        return entity.options?.tableName || stringUtils.pluralize(entity.name.toLowerCase());
    }
}