/**
 * Auth Helpers for Supabase
 * 
 * Generates authentication middleware, guards, and utilities
 */

import { stringUtils } from '@brickend/core';
import type {
    SupabaseConfig,
    AuthConfig,
    DatabaseSchema
} from '../types/index.js';

/**
 * Auth generation options
 */
interface AuthGenerationOptions {
    framework?: 'fastify' | 'express' | 'next' | 'generic';
    typescript?: boolean;
    includeRoles?: boolean;
    includePermissions?: boolean;
    customClaims?: boolean;
}

/**
 * Auth Helper Generator - Creates authentication code for different frameworks
 */
export class AuthHelperGenerator {
    private readonly config: SupabaseConfig;
    private readonly authConfig: AuthConfig;
    private readonly schema?: DatabaseSchema;

    constructor(config: SupabaseConfig, schema?: DatabaseSchema) {
        this.config = config;
        this.authConfig = config.auth || {};
        this.schema = schema;
    }

    /**
     * Generate authentication middleware
     */
    async generateAuthMiddleware(options: AuthGenerationOptions = {}): Promise<string> {
        const { framework = 'fastify', typescript = true, includeRoles = true } = options;

        const code: string[] = [];

        // Add file header
        code.push('/**');
        code.push(' * Authentication Middleware');
        code.push(' * Generated by Brickend - DO NOT EDIT');
        code.push(' */');
        code.push('');

        switch (framework) {
            case 'fastify':
                return this.generateFastifyMiddleware(code, typescript, includeRoles);
            case 'express':
                return this.generateExpressMiddleware(code, typescript, includeRoles);
            case 'next':
                return this.generateNextMiddleware(code, typescript, includeRoles);
            default:
                return this.generateGenericMiddleware(code, typescript, includeRoles);
        }
    }

    /**
     * Generate authentication guards
     */
    async generateAuthGuards(options: AuthGenerationOptions = {}): Promise<string> {
        const { framework = 'fastify', typescript = true, includeRoles = true, includePermissions = true } = options;

        const code: string[] = [];

        // Add file header
        code.push('/**');
        code.push(' * Authentication Guards');
        code.push(' * Generated by Brickend - DO NOT EDIT');
        code.push(' */');
        code.push('');

        // Add imports
        if (typescript) {
            code.push("import type { User } from '@supabase/supabase-js';");
            code.push('');
        }

        // Generate guard functions
        code.push('/**');
        code.push(' * Check if user is authenticated');
        code.push(' */');
        code.push(`export function requireAuth(user${typescript ? ': User | null' : ''})${typescript ? ': user is User' : ''} {`);
        code.push('  if (!user) {');
        code.push("    throw new Error('Authentication required');");
        code.push('  }');
        if (typescript) {
            code.push('  return true;');
        }
        code.push('}');
        code.push('');

        // Email verification guard
        if (this.authConfig.email?.confirmSignup) {
            code.push('/**');
            code.push(' * Check if user email is verified');
            code.push(' */');
            code.push(`export function requireEmailVerified(user${typescript ? ': User' : ''})${typescript ? ': boolean' : ''} {`);
            code.push('  if (!user.email_confirmed_at) {');
            code.push("    throw new Error('Email verification required');");
            code.push('  }');
            code.push('  return true;');
            code.push('}');
            code.push('');
        }

        // Role-based guards
        if (includeRoles) {
            code.push('/**');
            code.push(' * Check if user has required role');
            code.push(' */');
            code.push(`export function requireRole(user${typescript ? ': User' : ''}, role${typescript ? ': string' : ''})${typescript ? ': boolean' : ''} {`);
            code.push('  const userRole = user.user_metadata?.role || user.app_metadata?.role;');
            code.push('  if (userRole !== role) {');
            code.push(`    throw new Error(\`Role '\${role}' required\`);`);
            code.push('  }');
            code.push('  return true;');
            code.push('}');
            code.push('');

            code.push('/**');
            code.push(' * Check if user has any of the required roles');
            code.push(' */');
            code.push(`export function requireAnyRole(user${typescript ? ': User' : ''}, roles${typescript ? ': string[]' : ''})${typescript ? ': boolean' : ''} {`);
            code.push('  const userRole = user.user_metadata?.role || user.app_metadata?.role;');
            code.push('  if (!roles.includes(userRole)) {');
            code.push(`    throw new Error(\`One of roles [\${roles.join(', ')}] required\`);`);
            code.push('  }');
            code.push('  return true;');
            code.push('}');
            code.push('');

            // Admin guard
            code.push('/**');
            code.push(' * Check if user is admin');
            code.push(' */');
            code.push(`export function requireAdmin(user${typescript ? ': User' : ''})${typescript ? ': boolean' : ''} {`);
            code.push("  return requireRole(user, 'admin');");
            code.push('}');
            code.push('');
        }

        // Permission-based guards
        if (includePermissions) {
            code.push('/**');
            code.push(' * Check if user has required permission');
            code.push(' */');
            code.push(`export function requirePermission(user${typescript ? ': User' : ''}, permission${typescript ? ': string' : ''})${typescript ? ': boolean' : ''} {`);
            code.push('  const permissions = user.user_metadata?.permissions || user.app_metadata?.permissions || [];');
            code.push('  if (!permissions.includes(permission)) {');
            code.push(`    throw new Error(\`Permission '\${permission}' required\`);`);
            code.push('  }');
            code.push('  return true;');
            code.push('}');
            code.push('');

            code.push('/**');
            code.push(' * Check if user has any of the required permissions');
            code.push(' */');
            code.push(`export function requireAnyPermission(user${typescript ? ': User' : ''}, permissions${typescript ? ': string[]' : ''})${typescript ? ': boolean' : ''} {`);
            code.push('  const userPermissions = user.user_metadata?.permissions || user.app_metadata?.permissions || [];');
            code.push('  const hasPermission = permissions.some(p => userPermissions.includes(p));');
            code.push('  if (!hasPermission) {');
            code.push(`    throw new Error(\`One of permissions [\${permissions.join(', ')}] required\`);`);
            code.push('  }');
            code.push('  return true;');
            code.push('}');
            code.push('');
        }

        // Resource ownership guard
        if (this.schema) {
            code.push('/**');
            code.push(' * Check if user owns the resource');
            code.push(' */');
            code.push(`export function requireOwnership(user${typescript ? ': User' : ''}, resource${typescript ? ': { user_id?: string; owner_id?: string; created_by?: string }' : ''})${typescript ? ': boolean' : ''} {`);
            code.push('  const ownerId = resource.user_id || resource.owner_id || resource.created_by;');
            code.push('  if (ownerId !== user.id) {');
            code.push("    throw new Error('Resource ownership required');");
            code.push('  }');
            code.push('  return true;');
            code.push('}');
            code.push('');
        }

        // Combined guards
        code.push('/**');
        code.push(' * Guard combinations for common patterns');
        code.push(' */');
        code.push('export const guards = {');
        code.push(`  authenticated: requireAuth,`);
        if (this.authConfig.email?.confirmSignup) {
            code.push('  verified: (user: any) => {');
            code.push('    requireAuth(user);');
            code.push('    requireEmailVerified(user);');
            code.push('    return true;');
            code.push('  },');
        }
        if (includeRoles) {
            code.push('  admin: (user: any) => {');
            code.push('    requireAuth(user);');
            code.push("    requireRole(user, 'admin');");
            code.push('    return true;');
            code.push('  },');
            code.push('  moderator: (user: any) => {');
            code.push('    requireAuth(user);');
            code.push("    requireAnyRole(user, ['admin', 'moderator']);");
            code.push('    return true;');
            code.push('  },');
        }
        code.push('};');

        return code.join('\n');
    }

    /**
     * Generate authentication utilities
     */
    async generateAuthUtils(options: AuthGenerationOptions = {}): Promise<string> {
        const { typescript = true, customClaims = true } = options;

        const code: string[] = [];

        // Add file header
        code.push('/**');
        code.push(' * Authentication Utilities');
        code.push(' * Generated by Brickend - DO NOT EDIT');
        code.push(' */');
        code.push('');

        // Add imports
        code.push("import { createClient } from '@supabase/supabase-js';");
        if (typescript) {
            code.push("import type { User, Session } from '@supabase/supabase-js';");
        }
        code.push('');

        // JWT utilities
        code.push('/**');
        code.push(' * Extract user from JWT token');
        code.push(' */');
        code.push(`export async function getUserFromToken(token${typescript ? ': string' : ''})${typescript ? ': Promise<User | null>' : ''} {`);
        code.push('  try {');
        code.push('    const supabase = createClient(');
        code.push(`      '${this.config.url || `https://${this.config.projectId}.supabase.co`}',`);
        code.push(`      '${this.config.anonKey || 'your-anon-key'}'`);
        code.push('    );');
        code.push('');
        code.push('    const { data: { user }, error } = await supabase.auth.getUser(token);');
        code.push('    if (error) throw error;');
        code.push('    return user;');
        code.push('  } catch (error) {');
        code.push('    console.error("Failed to get user from token:", error);');
        code.push('    return null;');
        code.push('  }');
        code.push('}');
        code.push('');

        // Session utilities
        code.push('/**');
        code.push(' * Validate session');
        code.push(' */');
        code.push(`export async function validateSession(accessToken${typescript ? ': string' : ''})${typescript ? ': Promise<{ user: User; session: Session } | null>' : ''} {`);
        code.push('  try {');
        code.push('    const supabase = createClient(');
        code.push(`      '${this.config.url || `https://${this.config.projectId}.supabase.co`}',`);
        code.push(`      '${this.config.anonKey || 'your-anon-key'}'`);
        code.push('    );');
        code.push('');
        code.push('    const { data, error } = await supabase.auth.getUser(accessToken);');
        code.push('    if (error || !data.user) return null;');
        code.push('');
        code.push('    const { data: sessionData } = await supabase.auth.getSession();');
        code.push('    if (!sessionData.session) return null;');
        code.push('');
        code.push('    return { user: data.user, session: sessionData.session };');
        code.push('  } catch (error) {');
        code.push('    console.error("Session validation failed:", error);');
        code.push('    return null;');
        code.push('  }');
        code.push('}');
        code.push('');

        // Role utilities
        code.push('/**');
        code.push(' * Get user role');
        code.push(' */');
        code.push(`export function getUserRole(user${typescript ? ': User' : ''})${typescript ? ': string | null' : ''} {`);
        code.push('  return user.user_metadata?.role || user.app_metadata?.role || null;');
        code.push('}');
        code.push('');

        code.push('/**');
        code.push(' * Get user permissions');
        code.push(' */');
        code.push(`export function getUserPermissions(user${typescript ? ': User' : ''})${typescript ? ': string[]' : ''} {`);
        code.push('  return user.user_metadata?.permissions || user.app_metadata?.permissions || [];');
        code.push('}');
        code.push('');

        code.push('/**');
        code.push(' * Check if user has role');
        code.push(' */');
        code.push(`export function hasRole(user${typescript ? ': User' : ''}, role${typescript ? ': string' : ''})${typescript ? ': boolean' : ''} {`);
        code.push('  const userRole = getUserRole(user);');
        code.push('  return userRole === role;');
        code.push('}');
        code.push('');

        code.push('/**');
        code.push(' * Check if user has permission');
        code.push(' */');
        code.push(`export function hasPermission(user${typescript ? ': User' : ''}, permission${typescript ? ': string' : ''})${typescript ? ': boolean' : ''} {`);
        code.push('  const permissions = getUserPermissions(user);');
        code.push('  return permissions.includes(permission);');
        code.push('}');
        code.push('');

        // Custom claims utilities
        if (customClaims) {
            code.push('/**');
            code.push(' * Get custom claim value');
            code.push(' */');
            code.push(`export function getCustomClaim(user${typescript ? ': User' : ''}, claim${typescript ? ': string' : ''})${typescript ? ': any' : ''} {`);
            code.push('  return user.user_metadata?.[claim] || user.app_metadata?.[claim];');
            code.push('}');
            code.push('');

            code.push('/**');
            code.push(' * Set custom claim (requires admin privileges)');
            code.push(' */');
            code.push(`export async function setCustomClaim(userId${typescript ? ': string' : ''}, claim${typescript ? ': string' : ''}, value${typescript ? ': any' : ''})${typescript ? ': Promise<void>' : ''} {`);
            code.push('  const supabase = createClient(');
            code.push(`    '${this.config.url || `https://${this.config.projectId}.supabase.co`}',`);
            code.push(`    '${this.config.serviceRoleKey || 'your-service-role-key'}'`);
            code.push('  );');
            code.push('');
            code.push('  const { error } = await supabase.auth.admin.updateUserById(userId, {');
            code.push('    user_metadata: { [claim]: value }');
            code.push('  });');
            code.push('');
            code.push('  if (error) {');
            code.push(`    throw new Error(\`Failed to set custom claim: \${error.message}\`);`);
            code.push('  }');
            code.push('}');
            code.push('');
        }

        // Password utilities
        if (this.authConfig.password) {
            code.push('/**');
            code.push(' * Validate password strength');
            code.push(' */');
            code.push(`export function validatePassword(password${typescript ? ': string' : ''})${typescript ? ': { valid: boolean; errors: string[] }' : ''} {`);
            code.push('  const errors = [];');
            code.push('  const config = ' + JSON.stringify(this.authConfig.password, null, 2) + ';');
            code.push('');
            code.push('  if (config.minLength && password.length < config.minLength) {');
            code.push(`    errors.push(\`Password must be at least \${config.minLength} characters long\`);`);
            code.push('  }');
            code.push('');
            code.push('  if (config.requireUppercase && !/[A-Z]/.test(password)) {');
            code.push("    errors.push('Password must contain at least one uppercase letter');");
            code.push('  }');
            code.push('');
            code.push('  if (config.requireLowercase && !/[a-z]/.test(password)) {');
            code.push("    errors.push('Password must contain at least one lowercase letter');");
            code.push('  }');
            code.push('');
            code.push('  if (config.requireNumbers && !/[0-9]/.test(password)) {');
            code.push("    errors.push('Password must contain at least one number');");
            code.push('  }');
            code.push('');
            code.push('  if (config.requireSymbols && !/[^a-zA-Z0-9]/.test(password)) {');
            code.push("    errors.push('Password must contain at least one symbol');");
            code.push('  }');
            code.push('');
            code.push('  return { valid: errors.length === 0, errors };');
            code.push('}');
            code.push('');
        }

        // Error handling utilities
        code.push('/**');
        code.push(' * Handle authentication errors');
        code.push(' */');
        code.push(`export function handleAuthError(error${typescript ? ': any' : ''})${typescript ? ': { status: number; message: string }' : ''} {`);
        code.push('  if (!error) {');
        code.push('    return { status: 500, message: "Unknown authentication error" };');
        code.push('  }');
        code.push('');
        code.push('  switch (error.message) {');
        code.push('    case "Invalid login credentials":');
        code.push('      return { status: 401, message: "Invalid email or password" };');
        code.push('    case "Email not confirmed":');
        code.push('      return { status: 401, message: "Please verify your email address" };');
        code.push('    case "Invalid refresh token":');
        code.push('      return { status: 401, message: "Session expired, please login again" };');
        code.push('    case "User not found":');
        code.push('      return { status: 404, message: "User account not found" };');
        code.push('    case "Signup not allowed for this instance":');
        code.push('      return { status: 403, message: "Registration is currently disabled" };');
        code.push('    default:');
        code.push('      return { status: 400, message: error.message || "Authentication failed" };');
        code.push('  }');
        code.push('}');
        code.push('');

        // Rate limiting utilities
        code.push('/**');
        code.push(' * Simple rate limiting for auth endpoints');
        code.push(' */');
        code.push('const rateLimitMap = new Map();');
        code.push('');
        code.push(`export function checkRateLimit(identifier${typescript ? ': string' : ''}, maxAttempts${typescript ? ': number' : ''} = 5, windowMs${typescript ? ': number' : ''} = 15 * 60 * 1000)${typescript ? ': boolean' : ''} {`);
        code.push('  const now = Date.now();');
        code.push('  const windowStart = now - windowMs;');
        code.push('');
        code.push('  if (!rateLimitMap.has(identifier)) {');
        code.push('    rateLimitMap.set(identifier, []);');
        code.push('  }');
        code.push('');
        code.push('  const attempts = rateLimitMap.get(identifier);');
        code.push('  const recentAttempts = attempts.filter((time: number) => time > windowStart);');
        code.push('');
        code.push('  if (recentAttempts.length >= maxAttempts) {');
        code.push('    return false; // Rate limited');
        code.push('  }');
        code.push('');
        code.push('  recentAttempts.push(now);');
        code.push('  rateLimitMap.set(identifier, recentAttempts);');
        code.push('  return true; // Allowed');
        code.push('}');

        return code.join('\n');
    }

    /**
     * Generate Fastify middleware
     */
    private generateFastifyMiddleware(code: string[], typescript: boolean, includeRoles: boolean): string {
        // Add imports
        code.push("import { FastifyRequest, FastifyReply } from 'fastify';");
        code.push("import { getUserFromToken } from './auth-utils.js';");
        if (includeRoles) {
            code.push("import { requireAuth, requireRole } from './auth-guards.js';");
        }
        code.push('');

        // Extend FastifyRequest type
        if (typescript) {
            code.push('declare module "fastify" {');
            code.push('  interface FastifyRequest {');
            code.push('    user?: import("@supabase/supabase-js").User;');
            code.push('  }');
            code.push('}');
            code.push('');
        }

        // Auth middleware
        code.push('/**');
        code.push(' * Fastify authentication middleware');
        code.push(' */');
        code.push(`export async function authMiddleware(request${typescript ? ': FastifyRequest' : ''}, reply${typescript ? ': FastifyReply' : ''}) {`);
        code.push('  try {');
        code.push('    const authorization = request.headers.authorization;');
        code.push('    if (!authorization) {');
        code.push("      return reply.status(401).send({ error: 'Authorization header required' });");
        code.push('    }');
        code.push('');
        code.push('    const token = authorization.replace("Bearer ", "");');
        code.push('    const user = await getUserFromToken(token);');
        code.push('');
        code.push('    if (!user) {');
        code.push("      return reply.status(401).send({ error: 'Invalid token' });");
        code.push('    }');
        code.push('');
        code.push('    request.user = user;');
        code.push('  } catch (error) {');
        code.push("    return reply.status(401).send({ error: 'Authentication failed' });");
        code.push('  }');
        code.push('}');
        code.push('');

        // Optional auth middleware
        code.push('/**');
        code.push(' * Optional authentication middleware');
        code.push(' */');
        code.push(`export async function optionalAuthMiddleware(request${typescript ? ': FastifyRequest' : ''}, reply${typescript ? ': FastifyReply' : ''}) {`);
        code.push('  try {');
        code.push('    const authorization = request.headers.authorization;');
        code.push('    if (authorization) {');
        code.push('      const token = authorization.replace("Bearer ", "");');
        code.push('      const user = await getUserFromToken(token);');
        code.push('      request.user = user;');
        code.push('    }');
        code.push('  } catch (error) {');
        code.push('    // Ignore auth errors for optional middleware');
        code.push('  }');
        code.push('}');

        if (includeRoles) {
            code.push('');
            code.push('/**');
            code.push(' * Role-based middleware factory');
            code.push(' */');
            code.push(`export function requireRoleMiddleware(role${typescript ? ': string' : ''}) {`);
            code.push(`  return async function(request${typescript ? ': FastifyRequest' : ''}, reply${typescript ? ': FastifyReply' : ''}) {`);
            code.push('    try {');
            code.push('      if (!request.user) {');
            code.push("        return reply.status(401).send({ error: 'Authentication required' });");
            code.push('      }');
            code.push('      requireRole(request.user, role);');
            code.push('    } catch (error) {');
            code.push(`      return reply.status(403).send({ error: error.message });`);
            code.push('    }');
            code.push('  };');
            code.push('}');
        }

        return code.join('\n');
    }

    /**
     * Generate Express middleware
     */
    private generateExpressMiddleware(code: string[], typescript: boolean, includeRoles: boolean): string {
        // Add imports
        code.push("import { Request, Response, NextFunction } from 'express';");
        code.push("import { getUserFromToken } from './auth-utils.js';");
        if (includeRoles) {
            code.push("import { requireRole } from './auth-guards.js';");
        }
        code.push('');

        // Extend Express Request type
        if (typescript) {
            code.push('declare global {');
            code.push('  namespace Express {');
            code.push('    interface Request {');
            code.push('      user?: import("@supabase/supabase-js").User;');
            code.push('    }');
            code.push('  }');
            code.push('}');
            code.push('');
        }

        // Auth middleware
        code.push('/**');
        code.push(' * Express authentication middleware');
        code.push(' */');
        code.push(`export async function authMiddleware(req${typescript ? ': Request' : ''}, res${typescript ? ': Response' : ''}, next${typescript ? ': NextFunction' : ''}) {`);
        code.push('  try {');
        code.push('    const authorization = req.headers.authorization;');
        code.push('    if (!authorization) {');
        code.push("      return res.status(401).json({ error: 'Authorization header required' });");
        code.push('    }');
        code.push('');
        code.push('    const token = authorization.replace("Bearer ", "");');
        code.push('    const user = await getUserFromToken(token);');
        code.push('');
        code.push('    if (!user) {');
        code.push("      return res.status(401).json({ error: 'Invalid token' });");
        code.push('    }');
        code.push('');
        code.push('    req.user = user;');
        code.push('    next();');
        code.push('  } catch (error) {');
        code.push("    return res.status(401).json({ error: 'Authentication failed' });");
        code.push('  }');
        code.push('}');

        return code.join('\n');
    }

    /**
     * Generate Next.js middleware
     */
    private generateNextMiddleware(code: string[], typescript: boolean, includeRoles: boolean): string {
        // Add imports
        code.push("import { NextRequest, NextResponse } from 'next/server';");
        code.push("import { getUserFromToken } from './auth-utils.js';");
        code.push('');

        // Auth middleware
        code.push('/**');
        code.push(' * Next.js authentication middleware');
        code.push(' */');
        code.push(`export async function authMiddleware(request${typescript ? ': NextRequest' : ''}) {`);
        code.push('  try {');
        code.push('    const authorization = request.headers.get("authorization");');
        code.push('    if (!authorization) {');
        code.push('      return NextResponse.json({ error: "Authorization header required" }, { status: 401 });');
        code.push('    }');
        code.push('');
        code.push('    const token = authorization.replace("Bearer ", "");');
        code.push('    const user = await getUserFromToken(token);');
        code.push('');
        code.push('    if (!user) {');
        code.push('      return NextResponse.json({ error: "Invalid token" }, { status: 401 });');
        code.push('    }');
        code.push('');
        code.push('    // Add user to request headers for API routes');
        code.push('    const response = NextResponse.next();');
        code.push('    response.headers.set("x-user-id", user.id);');
        code.push('    response.headers.set("x-user-email", user.email || "");');
        code.push('    return response;');
        code.push('  } catch (error) {');
        code.push('    return NextResponse.json({ error: "Authentication failed" }, { status: 401 });');
        code.push('  }');
        code.push('}');

        return code.join('\n');
    }

    /**
     * Generate generic middleware
     */
    private generateGenericMiddleware(code: string[], typescript: boolean, includeRoles: boolean): string {
        // Add imports
        code.push("import { getUserFromToken } from './auth-utils.js';");
        code.push('');

        // Generic auth function
        code.push('/**');
        code.push(' * Generic authentication function');
        code.push(' */');
        code.push(`export async function authenticateRequest(headers${typescript ? ': Record<string, string>' : ''})${typescript ? ': Promise<import("@supabase/supabase-js").User | null>' : ''} {`);
        code.push('  try {');
        code.push('    const authorization = headers.authorization || headers.Authorization;');
        code.push('    if (!authorization) {');
        code.push('      return null;');
        code.push('    }');
        code.push('');
        code.push('    const token = authorization.replace("Bearer ", "");');
        code.push('    return await getUserFromToken(token);');
        code.push('  } catch (error) {');
        code.push('    return null;');
        code.push('  }');
        code.push('}');

        return code.join('\n');
    }
}