/**
 * Client Generator for Supabase
 * 
 * Generates optimized Supabase clients for different environments and use cases
 */

import { stringUtils } from '@brickend/core';
import type {
    Entity,
    Field
} from '@brickend/core';
import type {
    SupabaseConfig,
    ClientConfig,
    GeneratedClient,
    DatabaseSchema
} from '../types/index.js';

/**
 * Client generation options
 */
interface ClientGenerationOptions {
    includeTypes?: boolean;
    includeAuth?: boolean;
    includeStorage?: boolean;
    includeRealtime?: boolean;
    includeFunctions?: boolean;
    customMethods?: boolean;
    typescript?: boolean;
}

/**
 * Client Generator - Creates optimized Supabase clients
 */
export class ClientGenerator {
    private readonly config: SupabaseConfig;
    private readonly schema?: DatabaseSchema;

    constructor(config: SupabaseConfig, schema?: DatabaseSchema) {
        this.config = config;
        this.schema = schema;
    }

    /**
     * Generate server-side Supabase client
     */
    async generateServerClient(options: ClientGenerationOptions = {}): Promise<GeneratedClient> {
        const {
            includeTypes = true,
            includeAuth = true,
            includeStorage = false,
            includeRealtime = false,
            includeFunctions = true,
            customMethods = true,
            typescript = true
        } = options;

        const imports: string[] = [];
        const code: string[] = [];
        const exports: string[] = [];

        // Add file header
        code.push('/**');
        code.push(' * Supabase Server Client');
        code.push(' * Generated by Brickend - DO NOT EDIT');
        code.push(' */');
        code.push('');

        // Add imports
        imports.push("import { createClient } from '@supabase/supabase-js';");

        if (includeTypes && this.schema) {
            imports.push("import type { Database } from './types.js';");
        }

        code.push(...imports);
        code.push('');

        // Add environment variables validation
        code.push('// Environment variables validation');
        code.push('const supabaseUrl = process.env.SUPABASE_URL;');
        code.push('const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;');
        code.push('');
        code.push('if (!supabaseUrl || !supabaseServiceKey) {');
        code.push("  throw new Error('Missing Supabase environment variables');");
        code.push('}');
        code.push('');

        // Create server client
        const clientType = includeTypes && this.schema ? '<Database>' : '';
        code.push('// Server client with service role key');
        code.push(`export const supabaseServer = createClient${clientType}(`);
        code.push('  supabaseUrl,');
        code.push('  supabaseServiceKey,');
        code.push('  {');
        code.push('    auth: {');
        code.push('      autoRefreshToken: false,');
        code.push('      persistSession: false');
        code.push('    }');
        code.push('  }');
        code.push(');');
        code.push('');

        // Add auth client if needed
        if (includeAuth) {
            code.push('// Admin auth client');
            code.push(`export const supabaseAuth = createClient${clientType}(`);
            code.push('  supabaseUrl,');
            code.push('  supabaseServiceKey,');
            code.push('  {');
            code.push('    auth: {');
            code.push('      autoRefreshToken: false,');
            code.push('      persistSession: false');
            code.push('    }');
            code.push('  }');
            code.push(').auth.admin;');
            code.push('');
            exports.push('supabaseAuth');
        }

        // Add storage client if needed
        if (includeStorage) {
            code.push('// Storage client');
            code.push('export const supabaseStorage = supabaseServer.storage;');
            code.push('');
            exports.push('supabaseStorage');
        }

        // Add custom methods for entities
        if (customMethods && this.schema) {
            code.push('// Custom entity methods');
            code.push(...this.generateServerEntityMethods());
            code.push('');
        }

        // Add utility functions
        code.push('// Utility functions');
        code.push(...this.generateServerUtilityFunctions());

        exports.unshift('supabaseServer');

        return {
            filename: 'supabase-server.ts',
            content: code.join('\n'),
            type: 'server',
            exports
        };
    }

    /**
     * Generate browser-side Supabase client
     */
    async generateBrowserClient(options: ClientGenerationOptions = {}): Promise<GeneratedClient> {
        const {
            includeTypes = true,
            includeAuth = true,
            includeStorage = true,
            includeRealtime = true,
            includeFunctions = false,
            customMethods = true,
            typescript = true
        } = options;

        const imports: string[] = [];
        const code: string[] = [];
        const exports: string[] = [];

        // Add file header
        code.push('/**');
        code.push(' * Supabase Browser Client');
        code.push(' * Generated by Brickend - DO NOT EDIT');
        code.push(' */');
        code.push('');

        // Add imports
        imports.push("import { createClient } from '@supabase/supabase-js';");

        if (includeTypes && this.schema) {
            imports.push("import type { Database } from './types.js';");
        }

        code.push(...imports);
        code.push('');

        // Add environment variables (for client-side)
        code.push('// Environment variables for browser');
        code.push(`const supabaseUrl = '${this.config.url || `https://${this.config.projectId}.supabase.co`}';`);
        code.push(`const supabaseAnonKey = '${this.config.anonKey || 'your-anon-key-here'}';`);
        code.push('');

        // Create browser client
        const clientType = includeTypes && this.schema ? '<Database>' : '';
        code.push('// Browser client with anonymous key');
        code.push(`export const supabase = createClient${clientType}(`);
        code.push('  supabaseUrl,');
        code.push('  supabaseAnonKey,');
        code.push('  {');
        code.push('    auth: {');
        code.push('      autoRefreshToken: true,');
        code.push('      persistSession: true');
        code.push('    }');
        if (includeRealtime) {
            code.push('    realtime: {');
            code.push('      params: {');
            code.push('        eventsPerSecond: 2');
            code.push('      }');
            code.push('    }');
        }
        code.push('  }');
        code.push(');');
        code.push('');

        // Add auth helpers
        if (includeAuth) {
            code.push('// Auth helpers');
            code.push(...this.generateBrowserAuthHelpers());
            code.push('');
        }

        // Add storage helpers
        if (includeStorage) {
            code.push('// Storage helpers');
            code.push(...this.generateBrowserStorageHelpers());
            code.push('');
        }

        // Add realtime helpers
        if (includeRealtime) {
            code.push('// Realtime helpers');
            code.push(...this.generateBrowserRealtimeHelpers());
            code.push('');
        }

        // Add custom methods for entities
        if (customMethods && this.schema) {
            code.push('// Custom entity methods');
            code.push(...this.generateBrowserEntityMethods());
            code.push('');
        }

        exports.push('supabase');

        return {
            filename: 'supabase-browser.ts',
            content: code.join('\n'),
            type: 'browser',
            exports
        };
    }

    /**
     * Generate typed client with full type safety
     */
    async generateTypedClient(options: ClientGenerationOptions = {}): Promise<GeneratedClient> {
        if (!this.schema) {
            throw new Error('Schema is required for typed client generation');
        }

        const {
            includeAuth = true,
            includeStorage = true,
            includeRealtime = true,
            customMethods = true
        } = options;

        const imports: string[] = [];
        const code: string[] = [];
        const exports: string[] = [];

        // Add file header
        code.push('/**');
        code.push(' * Typed Supabase Client');
        code.push(' * Generated by Brickend - DO NOT EDIT');
        code.push(' */');
        code.push('');

        // Add imports
        imports.push("import { createClient, SupabaseClient } from '@supabase/supabase-js';");
        imports.push("import type { Database } from './types.js';");

        code.push(...imports);
        code.push('');

        // Generate typed client class
        code.push('/**');
        code.push(' * Typed Supabase client with full type safety');
        code.push(' */');
        code.push('export class TypedSupabaseClient {');
        code.push('  private client: SupabaseClient<Database>;');
        code.push('');
        code.push('  constructor(url: string, key: string) {');
        code.push('    this.client = createClient<Database>(url, key);');
        code.push('  }');
        code.push('');

        // Add typed methods for each entity
        for (const entity of this.schema.entities) {
            code.push(...this.generateTypedEntityMethods(entity));
            code.push('');
        }

        // Add auth methods if needed
        if (includeAuth) {
            code.push('  // Authentication methods');
            code.push('  get auth() {');
            code.push('    return this.client.auth;');
            code.push('  }');
            code.push('');
        }

        // Add storage methods if needed
        if (includeStorage) {
            code.push('  // Storage methods');
            code.push('  get storage() {');
            code.push('    return this.client.storage;');
            code.push('  }');
            code.push('');
        }

        // Add realtime methods if needed
        if (includeRealtime) {
            code.push('  // Realtime methods');
            code.push('  get realtime() {');
            code.push('    return this.client.realtime;');
            code.push('  }');
            code.push('');
        }

        code.push('  // Raw client access');
        code.push('  get raw() {');
        code.push('    return this.client;');
        code.push('  }');
        code.push('}');
        code.push('');

        // Add convenience factory function
        code.push('/**');
        code.push(' * Create a new typed Supabase client');
        code.push(' */');
        code.push('export function createTypedClient(url: string, key: string): TypedSupabaseClient {');
        code.push('  return new TypedSupabaseClient(url, key);');
        code.push('}');

        exports.push('TypedSupabaseClient', 'createTypedClient');

        return {
            filename: 'typed-client.ts',
            content: code.join('\n'),
            type: 'typed',
            exports
        };
    }

    /**
     * Generate server entity methods
     */
    private generateServerEntityMethods(): string[] {
        if (!this.schema) return [];

        const code: string[] = [];

        for (const entity of this.schema.entities) {
            const tableName = this.getTableName(entity);
            const entityName = stringUtils.camelCase(entity.name);
            const EntityName = stringUtils.pascalCase(entity.name);

            code.push(`// ${EntityName} methods`);
            code.push(`export const ${entityName} = {`);

            // Create method
            code.push('  async create(data: Database["public"]["Tables"]["' + tableName + '"]["Insert"]) {');
            code.push(`    return supabaseServer.from('${tableName}').insert(data).select().single();`);
            code.push('  },');
            code.push('');

            // Read methods
            code.push('  async findById(id: string) {');
            code.push(`    return supabaseServer.from('${tableName}').select().eq('id', id).single();`);
            code.push('  },');
            code.push('');

            code.push('  async findAll(options?: { limit?: number; offset?: number }) {');
            code.push('    let query = supabaseServer.from("' + tableName + '").select();');
            code.push('    if (options?.limit) query = query.limit(options.limit);');
            code.push('    if (options?.offset) query = query.range(options.offset, options.offset + (options.limit || 10) - 1);');
            code.push('    return query;');
            code.push('  },');
            code.push('');

            // Update method
            code.push('  async update(id: string, data: Database["public"]["Tables"]["' + tableName + '"]["Update"]) {');
            code.push(`    return supabaseServer.from('${tableName}').update(data).eq('id', id).select().single();`);
            code.push('  },');
            code.push('');

            // Delete method
            code.push('  async delete(id: string) {');
            code.push(`    return supabaseServer.from('${tableName}').delete().eq('id', id);`);
            code.push('  },');
            code.push('');

            // Soft delete if enabled
            if (entity.options?.softDelete) {
                code.push('  async softDelete(id: string) {');
                code.push(`    return supabaseServer.from('${tableName}').update({ deleted_at: new Date().toISOString() }).eq('id', id);`);
                code.push('  },');
                code.push('');
            }

            code.push('};');
            code.push('');
        }

        return code;
    }

    /**
     * Generate browser entity methods
     */
    private generateBrowserEntityMethods(): string[] {
        if (!this.schema) return [];

        const code: string[] = [];

        for (const entity of this.schema.entities) {
            const tableName = this.getTableName(entity);
            const entityName = stringUtils.camelCase(entity.name);
            const EntityName = stringUtils.pascalCase(entity.name);

            code.push(`// ${EntityName} methods`);
            code.push(`export const ${entityName} = {`);

            // Create method (user-scoped)
            code.push('  async create(data: Database["public"]["Tables"]["' + tableName + '"]["Insert"]) {');
            code.push(`    return supabase.from('${tableName}').insert(data).select().single();`);
            code.push('  },');
            code.push('');

            // Read methods (user-scoped)
            code.push('  async findById(id: string) {');
            code.push(`    return supabase.from('${tableName}').select().eq('id', id).single();`);
            code.push('  },');
            code.push('');

            code.push('  async findAll(options?: { limit?: number; offset?: number }) {');
            code.push('    let query = supabase.from("' + tableName + '").select();');
            code.push('    if (options?.limit) query = query.limit(options.limit);');
            code.push('    if (options?.offset) query = query.range(options.offset, options.offset + (options.limit || 10) - 1);');
            code.push('    return query;');
            code.push('  },');
            code.push('');

            // Update method
            code.push('  async update(id: string, data: Database["public"]["Tables"]["' + tableName + '"]["Update"]) {');
            code.push(`    return supabase.from('${tableName}').update(data).eq('id', id).select().single();`);
            code.push('  },');
            code.push('');

            // Delete method
            code.push('  async delete(id: string) {');
            code.push(`    return supabase.from('${tableName}').delete().eq('id', id);`);
            code.push('  },');
            code.push('');

            // Subscribe to changes
            code.push('  subscribe(callback: (payload: any) => void) {');
            code.push(`    return supabase`);
            code.push(`      .channel('${tableName}_changes')`);
            code.push(`      .on('postgres_changes', {`);
            code.push(`        event: '*',`);
            code.push(`        schema: 'public',`);
            code.push(`        table: '${tableName}'`);
            code.push(`      }, callback)`);
            code.push(`      .subscribe();`);
            code.push('  },');
            code.push('');

            code.push('};');
            code.push('');
        }

        return code;
    }

    /**
     * Generate typed entity methods
     */
    private generateTypedEntityMethods(entity: Entity): string[] {
        const tableName = this.getTableName(entity);
        const entityName = stringUtils.camelCase(entity.name);
        const EntityName = stringUtils.pascalCase(entity.name);

        const code: string[] = [];

        code.push(`  // ${EntityName} methods`);
        code.push(`  get ${entityName}() {`);
        code.push('    return {');

        // Create method with full typing
        code.push('      create: async (data: Database["public"]["Tables"]["' + tableName + '"]["Insert"]) => {');
        code.push(`        return this.client.from('${tableName}').insert(data).select().single();`);
        code.push('      },');
        code.push('');

        // Read methods with full typing
        code.push('      findById: async (id: string) => {');
        code.push(`        return this.client.from('${tableName}').select().eq('id', id).single();`);
        code.push('      },');
        code.push('');

        code.push('      findAll: async (options?: { limit?: number; offset?: number }) => {');
        code.push('        let query = this.client.from("' + tableName + '").select();');
        code.push('        if (options?.limit) query = query.limit(options.limit);');
        code.push('        if (options?.offset) query = query.range(options.offset, options.offset + (options.limit || 10) - 1);');
        code.push('        return query;');
        code.push('      },');
        code.push('');

        // Update method with full typing
        code.push('      update: async (id: string, data: Database["public"]["Tables"]["' + tableName + '"]["Update"]) => {');
        code.push(`        return this.client.from('${tableName}').update(data).eq('id', id).select().single();`);
        code.push('      },');
        code.push('');

        // Delete method
        code.push('      delete: async (id: string) => {');
        code.push(`        return this.client.from('${tableName}').delete().eq('id', id);`);
        code.push('      },');
        code.push('');

        // Query builder access
        code.push('      query: () => {');
        code.push(`        return this.client.from('${tableName}');`);
        code.push('      }');

        code.push('    };');
        code.push('  }');

        return code;
    }

    /**
     * Generate server utility functions
     */
    private generateServerUtilityFunctions(): string[] {
        const code: string[] = [];

        code.push('/**');
        code.push(' * Execute raw SQL query');
        code.push(' */');
        code.push('export async function executeSQL(sql: string) {');
        code.push("  return supabaseServer.rpc('exec_sql', { sql });");
        code.push('}');
        code.push('');

        code.push('/**');
        code.push(' * Get database health status');
        code.push(' */');
        code.push('export async function getHealthStatus() {');
        code.push("  try {");
        code.push("    const { data, error } = await supabaseServer.from('_brickend_migrations').select('count').limit(1);");
        code.push("    return { healthy: !error, error: error?.message };");
        code.push("  } catch (err) {");
        code.push("    return { healthy: false, error: 'Connection failed' };");
        code.push("  }");
        code.push('}');

        return code;
    }

    /**
     * Generate browser auth helpers
     */
    private generateBrowserAuthHelpers(): string[] {
        const code: string[] = [];

        code.push('export const auth = {');
        code.push('  signUp: (email: string, password: string) => {');
        code.push('    return supabase.auth.signUp({ email, password });');
        code.push('  },');
        code.push('');
        code.push('  signIn: (email: string, password: string) => {');
        code.push('    return supabase.auth.signInWithPassword({ email, password });');
        code.push('  },');
        code.push('');
        code.push('  signOut: () => {');
        code.push('    return supabase.auth.signOut();');
        code.push('  },');
        code.push('');
        code.push('  getUser: () => {');
        code.push('    return supabase.auth.getUser();');
        code.push('  },');
        code.push('');
        code.push('  onAuthChange: (callback: (event: string, session: any) => void) => {');
        code.push('    return supabase.auth.onAuthStateChange(callback);');
        code.push('  }');
        code.push('};');

        return code;
    }

    /**
     * Generate browser storage helpers
     */
    private generateBrowserStorageHelpers(): string[] {
        const code: string[] = [];

        code.push('export const storage = {');
        code.push('  upload: (bucket: string, path: string, file: File) => {');
        code.push('    return supabase.storage.from(bucket).upload(path, file);');
        code.push('  },');
        code.push('');
        code.push('  download: (bucket: string, path: string) => {');
        code.push('    return supabase.storage.from(bucket).download(path);');
        code.push('  },');
        code.push('');
        code.push('  getPublicUrl: (bucket: string, path: string) => {');
        code.push('    return supabase.storage.from(bucket).getPublicUrl(path);');
        code.push('  },');
        code.push('');
        code.push('  delete: (bucket: string, paths: string[]) => {');
        code.push('    return supabase.storage.from(bucket).remove(paths);');
        code.push('  }');
        code.push('};');

        return code;
    }

    /**
     * Generate browser realtime helpers
     */
    private generateBrowserRealtimeHelpers(): string[] {
        const code: string[] = [];

        code.push('export const realtime = {');
        code.push('  subscribe: (table: string, callback: (payload: any) => void) => {');
        code.push('    return supabase');
        code.push("      .channel(`${table}_changes`)");
        code.push("      .on('postgres_changes', {");
        code.push("        event: '*',");
        code.push("        schema: 'public',");
        code.push('        table');
        code.push('      }, callback)');
        code.push('      .subscribe();');
        code.push('  },');
        code.push('');
        code.push('  unsubscribe: (channel: any) => {');
        code.push('    return supabase.removeChannel(channel);');
        code.push('  }');
        code.push('};');

        return code;
    }

    /**
     * Get table name for entity
     */
    private getTableName(entity: Entity): string {
        return entity.options?.tableName || stringUtils.pluralize(entity.name.toLowerCase());
    }
}